/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadegarantias;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sistemadegarantias.Configuracionserver.IPSUCURSAL;
import static sistemadegarantias.Configuracionserver.SUCURSAL;

/**
 *
 * @author AGONZALEZ
 */
public class DETALLEVENTA extends javax.swing.JFrame {
    Statement st;
    PreparedStatement ps = null;
    ResultSet rs;
   
    DefaultTableModel md;
    int count = 0; 
    /**
     * Creates new form DETALLEVENTA
     */
    
    public void Enviardatos(){
    
    
        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
              java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://"+IPSUCURSAL+"", "usounds", "madljda");               
            st = conexion.createStatement();
            st.executeUpdate("USE CML;");

            //Seleccionar datos
            rs = st.executeQuery("select v.codigo, \n"
                    + "(select descripcion from codigos where codigo=cg.codigo)as descgenero,\n"
                    + "cg.garantia, v.cantidad,sum(cantidad*precioventaneto)as precio\n"
                    + "from ventas v, codigosgarantias cg \n"
                    + "where v.codigo=cg.codigo and v.fecha='" + JTDVFECHA.getText() + "' and v.caja='" + JTDVCAJA.getText() + "' and v.folio='" + JTDVFOLIO.getText() + "' and v.sucursal='" + JTDVSUC.getText() + "'\n"
                    + "group by v.codigo,cg.codigo,cg.garantia,v.cantidad");

            md = (DefaultTableModel) JTableDV.getModel();
            md.setRowCount(0);
            while (rs.next()) {
                count = count + 1;
                Object[] fila = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getInt(4), rs.getDouble(5)};
                md.addRow(fila);
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la base de datos");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DETALLEVENTA.class.getName()).log(Level.SEVERE, null, ex);
        }


    
    
    
    
    }
    
    
    
    
    
    public DETALLEVENTA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDV = new javax.swing.JTable();
        Cerrar_ventana = new javax.swing.JToggleButton();
        JTDVFOLIO = new javax.swing.JLabel();
        JTDVFECHA = new javax.swing.JLabel();
        JTDVCAJA = new javax.swing.JLabel();
        JTDVSUC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DETALLE DE VENTA - SOUNDS");
        setMinimumSize(new java.awt.Dimension(750, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETALLE VENTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 370, 60));

        JTableDV.setAutoCreateRowSorter(true);
        JTableDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTableDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION", "GARANTIA", "CANTIDAD", "PRECIO"
            }
        ));
        JTableDV.setRowHeight(50);
        jScrollPane1.setViewportView(JTableDV);
        if (JTableDV.getColumnModel().getColumnCount() > 0) {
            JTableDV.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
            JTableDV.getColumnModel().getColumn(1).setHeaderValue("DESCRIPCION");
            JTableDV.getColumnModel().getColumn(2).setHeaderValue("GARANTIA");
            JTableDV.getColumnModel().getColumn(3).setHeaderValue("CANTIDAD");
            JTableDV.getColumnModel().getColumn(4).setHeaderValue("PRECIO");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 630, 150));

        Cerrar_ventana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cerrar_ventana.setText("CERRAR");
        Cerrar_ventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_ventanaActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 50));
        getContentPane().add(JTDVFOLIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 20, 20));
        getContentPane().add(JTDVFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 20, 30));
        getContentPane().add(JTDVCAJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 50, 20));

        JTDVSUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/TP3.jpg"))); // NOI18N
        JTDVSUC.setText("jLabel2");
        getContentPane().add(JTDVSUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cerrar_ventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_ventanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Cerrar_ventanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DETALLEVENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DETALLEVENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DETALLEVENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DETALLEVENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DETALLEVENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cerrar_ventana;
    public javax.swing.JLabel JTDVCAJA;
    public javax.swing.JLabel JTDVFECHA;
    public javax.swing.JLabel JTDVFOLIO;
    public javax.swing.JLabel JTDVSUC;
    private javax.swing.JTable JTableDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
